{
	"vulinfoid": "JVNDB-2023-011526",
	"vulinfodata": {
		"title": "Python Software Foundation の Python における脆弱性",
		"vulinfodescription": {
			"overview": "Python Software Foundation の Python には、不特定の脆弱性が存在します。"
		},
		"affected": {
			"affecteditem": [
				{
					"name": "Python Software Foundation",
					"productname": "Python",
					"cpe": {
						"text": "cpe:/a:python:python",
						"version": "2.2"
					},
					"versionnumber": [
						"3.10.0 以上 3.10.13 未満",
						"3.11.0 以上 3.11.5 未満",
						"3.8.18 未満",
						"3.9.0 以上 3.9.18 未満"
					]
				}
			]
		},
		"impact": {
			"cvss": [
				{
					"version": "3.0",
					"severity": {
						"text": "Medium",
						"type": "Base"
					},
					"base": "5.3",
					"vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N"
				}
			],
			"impactitem": {
				"description": "情報を取得される可能性があります。"
			}
		},
		"solution": {
			"solutionitem": {
				"description": "ベンダアドバイザリまたはパッチ情報が公開されています。参考情報を参照して適切な対策を実施してください。"
			}
		},
		"related": {
			"relateditem": [
				{
					"type": "advisory",
					"name": "Common Vulnerabilities and Exposures (CVE)",
					"vulinfoid": "CVE-2023-40217",
					"url": "https://www.cve.org/CVERecord?id=CVE-2023-40217"
				},
				{
					"type": "advisory",
					"name": "National Vulnerability Database (NVD)",
					"vulinfoid": "CVE-2023-40217",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2023-40217"
				},
				{
					"type": "advisory",
					"name": "関連文書",
					"vulinfoid": "lists.debian.org (msg00017)",
					"url": "https://lists.debian.org/debian-lts-announce/2023/10/msg00017.html"
				},
				{
					"type": "advisory",
					"name": "関連文書",
					"vulinfoid": "mail.python.org (PEPLII27KYHLF4AK3ZQGKYNCRERG4YXY)",
					"url": "https://mail.python.org/archives/list/security-announce%40python.org/thread/PEPLII27KYHLF4AK3ZQGKYNCRERG4YXY/"
				},
				{
					"type": "advisory",
					"name": "関連文書",
					"vulinfoid": "security.netapp.com (ntap-20231006-0014)",
					"url": "https://security.netapp.com/advisory/ntap-20231006-0014/"
				},
				{
					"type": "advisory",
					"name": "関連文書",
					"vulinfoid": "www.python.org (security)",
					"url": "https://www.python.org/dev/security/"
				},
				{
					"type": "advisory",
					"name": "関連文書",
					"vulinfoid": "lists.debian.org (msg00022)",
					"url": "https://lists.debian.org/debian-lts-announce/2023/09/msg00022.html"
				},
				{
					"type": "cwe",
					"name": "JVNDB",
					"vulinfoid": "CWE-noinfo",
					"url": "https://www.ipa.go.jp/security/vuln/scap/cwe.html",
					"title": "情報不足"
				}
			]
		},
		"history": {
			"historyitem": [
				{
					"historyno": "1",
					"datetime": "2023-12-13T16:16:29+09:00",
					"description": "[2023年12月13日]\\n  掲載"
				}
			]
		},
		"datefirstpublished": "2023-12-13T16:16:29+09:00",
		"datelastupdated": "2023-12-13T16:16:29+09:00",
		"datepublic": "2023-08-25T00:00:00+09:00"
	}
}
