{
	"vulinfoid": "JVNDB-2023-022187",
	"vulinfodata": {
		"title": "Python Software Foundation の Python における脆弱性",
		"vulinfodescription": {
			"overview": "Python Software Foundation の Python には、不特定の脆弱性が存在します。"
		},
		"affected": {
			"affecteditem": [
				{
					"name": "Python Software Foundation",
					"productname": "Python",
					"cpe": {
						"text": "cpe:/a:python:python",
						"version": "2.2"
					},
					"versionnumber": [
						"3.13.0"
					]
				}
			]
		},
		"impact": {
			"cvss": [
				{
					"version": "3.0",
					"severity": {
						"text": "Medium",
						"type": "Base"
					},
					"base": "5.3",
					"vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N"
				}
			],
			"impactitem": {
				"description": "情報を取得される可能性があります。"
			}
		},
		"solution": {
			"solutionitem": {
				"description": "ベンダアドバイザリまたはパッチ情報が公開されています。参考情報を参照して適切な対策を実施してください。"
			}
		},
		"related": {
			"relateditem": [
				{
					"type": "advisory",
					"name": "Common Vulnerabilities and Exposures (CVE)",
					"vulinfoid": "CVE-2023-38898",
					"url": "https://www.cve.org/CVERecord?id=CVE-2023-38898"
				},
				{
					"type": "advisory",
					"name": "National Vulnerability Database (NVD)",
					"vulinfoid": "CVE-2023-38898",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2023-38898"
				},
				{
					"type": "advisory",
					"name": "関連文書",
					"vulinfoid": "github.com (issues/105987)",
					"url": "https://github.com/python/cpython/issues/105987"
				},
				{
					"type": "cwe",
					"name": "JVNDB",
					"vulinfoid": "CWE-Other",
					"url": "https://www.ipa.go.jp/security/vuln/scap/cwe.html",
					"title": "その他"
				}
			]
		},
		"history": {
			"historyitem": [
				{
					"historyno": "1",
					"datetime": "2024-01-22T14:08:17+09:00",
					"description": "[2024年01月22日]\\n  掲載"
				}
			]
		},
		"datefirstpublished": "2024-01-22T14:08:17+09:00",
		"datelastupdated": "2024-01-22T14:08:17+09:00",
		"datepublic": "2023-08-15T00:00:00+09:00"
	}
}
