{
  "vulinfoid": "JVNDB-2014-003934",
  "vulinfodata": {
    "title": "Python Image Library および Pillow の PIL/IcnsImagePlugin.py におけるサービス運用妨害 (DoS) の脆弱性",
    "vulinfodescription": {
      "overview": "Python Image Library (PIL) および Pillow の PIL/IcnsImagePlugin.py には、サービス運用妨害 (DoS) 状態にされる脆弱性が存在します。"
    },
    "affected": {
      "affecteditem": [
        {
          "name": "Debian",
          "productname": "Python Imaging",
          "cpe": {
            "text": "cpe:/a:debian:python-imaging",
            "version": "2.2"
          }
        },
        {
          "name": "Python Software Foundation",
          "productname": "Python Pillow",
          "cpe": {
            "text": "cpe:/a:python:pillow",
            "version": "2.2"
          },
          "versionnumber": [
            "2.3.2 未満",
            "2.5.2 未満の 2.5.x"
          ]
        }
      ]
    },
    "impact": {
      "cvss": [
        {
          "version": "2.0",
          "severity": {
            "text": "Medium",
            "type": "Base"
          },
          "base": "5",
          "vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P"
        }
      ],
      "impactitem": {
        "description": "第三者により、巧妙に細工されたブロックサイズを介して、サービス運用妨害 (DoS) 状態にされる可能性があります。"
      }
    },
    "solution": {
      "solutionitem": {
        "description": "ベンダより正式な対策が公開されています。ベンダ情報を参照して適切な対策を実施してください。"
      }
    },
    "related": {
      "relateditem": [
        {
          "type": "vendor",
          "name": "Debian Security Advisory",
          "vulinfoid": "DSA-3009",
          "url": "https://www.debian.org/security/2014/dsa-3009"
        },
        {
          "type": "vendor",
          "name": "GitHub",
          "vulinfoid": "python-pillow/Pillow",
          "url": "https://github.com/python-pillow/Pillow/commit/205e056f8f9b06ed7b925cf8aa0874bc4aaf8a7d"
        },
        {
          "type": "vendor",
          "name": "Python",
          "vulinfoid": "Pillow 2.5.2",
          "url": "https://pypi.python.org/pypi/Pillow/2.5.2"
        },
        {
          "type": "vendor",
          "name": "Python",
          "vulinfoid": "Pillow 2.3.2",
          "url": "https://pypi.python.org/pypi/Pillow/2.3.2"
        },
        {
          "type": "advisory",
          "name": "Common Vulnerabilities and Exposures (CVE)",
          "vulinfoid": "CVE-2014-3589",
          "url": "http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-3589"
        },
        {
          "type": "advisory",
          "name": "National Vulnerability Database (NVD)",
          "vulinfoid": "CVE-2014-3589",
          "url": "http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2014-3589"
        },
        {
          "type": "cwe",
          "name": "JVNDB",
          "vulinfoid": "CWE-20",
          "url": "https://jvndb.jvn.jp/ja/cwe/CWE-20.html",
          "title": "不適切な入力確認"
        }
      ]
    },
    "history": {
      "historyitem": [
        {
          "historyno": "0",
          "datetime": "2018-02-17T10:37:52+09:00",
          "description": "[2014年08月27日]\\n  掲載"
        }
      ]
    },
    "datefirstpublished": "2014-08-27T12:25:36+09:00",
    "datelastupdated": "2014-08-27T12:25:36+09:00",
    "datepublic": "2014-08-13T00:00:00+09:00"
  }
}
