{
  "vulinfoid": "JVNDB-2019-012898",
  "vulinfodata": {
    "title": "python-ecdsa における例外的な状態の処理に関する脆弱性",
    "vulinfodescription": {
      "overview": "python-ecdsa には、例外的な状態の処理に関する脆弱性が存在します。 "
    },
    "affected": {
      "affecteditem": [
        {
          "name": "python-ecdsa project",
          "productname": "python-ecdsa",
          "cpe": {
            "text": "cpe:/a:python-ecdsa_project:python-ecdsa",
            "version": "2.2"
          },
          "versionnumber": [
            "0.13.3 未満"
          ]
        }
      ]
    },
    "impact": {
      "cvss": [
        {
          "version": "2.0",
          "severity": {
            "text": "Medium",
            "type": "Base"
          },
          "base": "5",
          "vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P"
        },
        {
          "version": "3.0",
          "severity": {
            "text": "High",
            "type": "Base"
          },
          "base": "7.5",
          "vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
        }
      ],
      "impactitem": {
        "description": "サービス運用妨害 (DoS) 状態にされる可能性があります。"
      }
    },
    "solution": {
      "solutionitem": {
        "description": "ベンダより正式な対策が公開されています。ベンダ情報を参照して適切な対策を実施してください。"
      }
    },
    "related": {
      "relateditem": [
        {
          "type": "vendor",
          "name": "GitHub",
          "vulinfoid": "ecdsa 0.13.3",
          "url": "https://github.com/warner/python-ecdsa/releases/tag/python-ecdsa-0.13.3"
        },
        {
          "type": "advisory",
          "name": "Common Vulnerabilities and Exposures (CVE)",
          "vulinfoid": "CVE-2019-14853",
          "url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-14853"
        },
        {
          "type": "advisory",
          "name": "National Vulnerability Database (NVD)",
          "vulinfoid": "CVE-2019-14853",
          "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-14853"
        },
        {
          "type": "cwe",
          "name": "JVNDB",
          "vulinfoid": "CWE-755",
          "url": "https://cwe.mitre.org/data/definitions/755.html",
          "title": "例外的な状態における不適切な処理"
        }
      ]
    },
    "history": {
      "historyitem": [
        {
          "historyno": "1",
          "datetime": "2019-12-16T16:35:11+09:00",
          "description": "[2019年12月16日]\\n  掲載"
        }
      ]
    },
    "datefirstpublished": "2019-12-16T16:35:13+09:00",
    "datelastupdated": "2019-12-16T16:35:13+09:00",
    "datepublic": "2019-10-07T00:00:00+09:00"
  }
}
