{
  "vulinfoid": "JVNDB-2020-004781",
  "vulinfodata": {
    "title": "Xen における例外的な状態の処理に関する脆弱性",
    "vulinfodescription": {
      "overview": "Xen には、例外的な状態の処理に関する脆弱性が存在します。"
    },
    "affected": {
      "affecteditem": [
        {
          "name": "Fedora Project",
          "productname": "Fedora",
          "cpe": {
            "text": "cpe:/o:fedoraproject:fedora",
            "version": "2.2"
          }
        },
        {
          "name": "Xen プロジェクト",
          "productname": "Xen",
          "cpe": {
            "text": "cpe:/o:xen:xen",
            "version": "2.2"
          }
        }
      ]
    },
    "impact": {
      "cvss": [
        {
          "version": "2.0",
          "severity": {
            "text": "Low",
            "type": "Base"
          },
          "base": "2.1",
          "vector": "AV:L/AC:L/Au:N/C:N/I:N/A:P"
        },
        {
          "version": "3.0",
          "severity": {
            "text": "Medium",
            "type": "Base"
          },
          "base": "5.5",
          "vector": "CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
        }
      ],
      "impactitem": {
        "description": "サービス運用妨害 (DoS) 状態にされる可能性があります。"
      }
    },
    "solution": {
      "solutionitem": {
        "description": "ベンダより正式な対策が公開されています。ベンダ情報を参照して適切な対策を実施してください。"
      }
    },
    "related": {
      "relateditem": [
        {
          "type": "vendor",
          "name": "Fedora Update Notification",
          "vulinfoid": "FEDORA-2020-295ed0b1e0",
          "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5M2XRNCHOGGTJQBZQJ7DCV6ZNAKN3LE2/"
        },
        {
          "type": "vendor",
          "name": "Fedora Update Notification",
          "vulinfoid": "FEDORA-2020-cbc3149753",
          "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NVTP4OYHCTRU3ONFJOFJQVNDFB25KLLG/"
        },
        {
          "type": "vendor",
          "name": "Fedora Update Notification",
          "vulinfoid": "FEDORA-2020-440457afe4",
          "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YMAW7D2MP6RE4BFI5BZWOBBWGY3VSOFN/"
        },
        {
          "type": "vendor",
          "name": "Xen Security Advisory",
          "vulinfoid": "XSA-316",
          "url": "https://xenbits.xen.org/xsa/advisory-316.html"
        },
        {
          "type": "advisory",
          "name": "Common Vulnerabilities and Exposures (CVE)",
          "vulinfoid": "CVE-2020-11743",
          "url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-11743"
        },
        {
          "type": "advisory",
          "name": "National Vulnerability Database (NVD)",
          "vulinfoid": "CVE-2020-11743",
          "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-11743"
        },
        {
          "type": "advisory",
          "name": "関連文書",
          "vulinfoid": "Xen Security Advisory 316 v3 (CVE-2020-11743) - Bad error path in GNTTABOP_map_grant",
          "url": "https://www.openwall.com/lists/oss-security/2020/04/14/3"
        },
        {
          "type": "cwe",
          "name": "JVNDB",
          "vulinfoid": "CWE-755",
          "url": "https://cwe.mitre.org/data/definitions/755.html",
          "title": "例外的な状態における不適切な処理"
        }
      ]
    },
    "history": {
      "historyitem": [
        {
          "historyno": "1",
          "datetime": "2020-05-27T18:05:10+09:00",
          "description": "[2020年05月27日]\\n  掲載"
        }
      ]
    },
    "datefirstpublished": "2020-05-27T18:05:10+09:00",
    "datelastupdated": "2020-05-27T18:05:10+09:00",
    "datepublic": "2020-04-14T00:00:00+09:00"
  }
}
