{
  "vulinfoid": "JVNDB-2020-010264",
  "vulinfodata": {
    "title": "MongoDB Server における例外的な状態の処理に関する脆弱性",
    "vulinfodescription": {
      "overview": "MongoDB Server には、例外的な状態の処理に関する脆弱性が存在します。"
    },
    "affected": {
      "affecteditem": [
        {
          "name": "Debian",
          "productname": "Debian GNU/Linux",
          "cpe": {
            "text": "cpe:/o:debian:debian_linux",
            "version": "2.2"
          }
        },
        {
          "name": "MongoDB Inc.",
          "productname": "MongoDB",
          "cpe": {
            "text": "cpe:/a:mongodb:mongodb",
            "version": "2.2"
          },
          "versionnumber": [
            "4.0.19 未満の 4.0",
            "4.2.8 未満の 4.2",
            "4.4.0-rc7 未満の 4.4",
            "4.5.1 未満の 4.5"
          ]
        }
      ]
    },
    "impact": {
      "cvss": [
        {
          "version": "2.0",
          "severity": {
            "text": "Medium",
            "type": "Base"
          },
          "base": "4",
          "vector": "AV:N/AC:L/Au:S/C:N/I:N/A:P"
        },
        {
          "version": "3.0",
          "severity": {
            "text": "Medium",
            "type": "Base"
          },
          "base": "6.5",
          "vector": "CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
        }
      ],
      "impactitem": {
        "description": "サービス運用妨害 (DoS) 状態にされる可能性があります。"
      }
    },
    "solution": {
      "solutionitem": {
        "description": "ベンダより正式な対策が公開されています。ベンダ情報を参照して適切な対策を実施してください。"
      }
    },
    "related": {
      "relateditem": [
        {
          "type": "vendor",
          "name": "debian-security-announce",
          "vulinfoid": "[SECURITY] [DLA 2344-1] mongodb security update",
          "url": "https://lists.debian.org/debian-lts-announce/2020/08/msg00041.html"
        },
        {
          "type": "vendor",
          "name": "MongoDB",
          "vulinfoid": "SERVER-47773",
          "url": "https://jira.mongodb.org/browse/SERVER-47773"
        },
        {
          "type": "advisory",
          "name": "Common Vulnerabilities and Exposures (CVE)",
          "vulinfoid": "CVE-2020-7923",
          "url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-7923"
        },
        {
          "type": "advisory",
          "name": "National Vulnerability Database (NVD)",
          "vulinfoid": "CVE-2020-7923",
          "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-7923"
        },
        {
          "type": "cwe",
          "name": "JVNDB",
          "vulinfoid": "CWE-755",
          "url": "https://cwe.mitre.org/data/definitions/755.html",
          "title": "例外的な状態における不適切な処理"
        }
      ]
    },
    "history": {
      "historyitem": [
        {
          "historyno": "1",
          "datetime": "2021-01-04T16:14:37+09:00",
          "description": "[2021年01月04日]\\n  掲載"
        }
      ]
    },
    "datefirstpublished": "2021-01-04T16:14:37+09:00",
    "datelastupdated": "2021-01-04T16:14:37+09:00",
    "datepublic": "2020-05-01T00:00:00+09:00"
  }
}
